/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desktopfilemaker;

import java.awt.Image;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * XFCE-style Linux Desktop File Creator & Editor window.
 * 
 * @author chr0no2
 */
public class Main extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        initCustomComponents();
    }

    private void initCustomComponents() {
        setTitle("Create Launcher");
        setLocationRelativeTo(null);
        updateIconPreview();
        
        txtIcon.addActionListener(evt -> updateIconPreview());
        txtIcon.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateIconPreview();
            }
        });
    }

    /**
     * Updates the icon preview label based on the icon text field.
     */
    private void updateIconPreview() {
        String iconPath = txtIcon.getText().trim();
        if (iconPath.isEmpty()) {
            lblIconPreview.setIcon(null);
            lblIconPreview.setText("N/A");
            return;
        }

        File iconFile = new File(iconPath);
        if (iconFile.exists() && iconFile.isFile()) {
            try {
                ImageIcon originalIcon = new ImageIcon(iconFile.getAbsolutePath());
                Image scaledImage = originalIcon.getImage().getScaledInstance(32, 32, Image.SCALE_SMOOTH);
                lblIconPreview.setIcon(new ImageIcon(scaledImage));
                lblIconPreview.setText("");
                return;
            } catch (Exception ex) {
                logger.log(Level.FINE, "Failed to render image file preview", ex);
            }
        }
        
        lblIconPreview.setIcon(null);
        lblIconPreview.setText("[" + iconPath + "]");
    }

    public void clearFields() {
        txtName.setText("");
        txtComment.setText("");
        txtCommand.setText("");
        txtWorkDir.setText("");
        txtIcon.setText("");
        txtCategories.setText("");
        chkTerminal.setSelected(false);
        chkStartupNotify.setSelected(false);
        updateIconPreview();
        setTitle("Create Launcher");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOpen = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtComment = new javax.swing.JTextField();
        txtCommand = new javax.swing.JTextField();
        txtWorkDir = new javax.swing.JTextField();
        txtIcon = new javax.swing.JTextField();
        txtCategories = new javax.swing.JTextField();
        btnSelectCategories = new javax.swing.JButton();
        btnBrowseCommand = new javax.swing.JButton();
        btnBrowseWorkDir = new javax.swing.JButton();
        btnPickIcon = new javax.swing.JButton();
        lblIconPreview = new javax.swing.JLabel();
        chkStartupNotify = new javax.swing.JCheckBox();
        chkTerminal = new javax.swing.JCheckBox();
        chkShowHidden = new javax.swing.JCheckBox();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Launcher");

        btnOpen.setText("Open Desktop File...");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnClear.setText("Clear Fields");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("Comment:");

        jLabel3.setText("Command:");

        jLabel4.setText("Working Directory:");

        jLabel5.setText("Icon:");

        jLabel7.setText("Categories:");

        jLabel6.setText("Options:");

        btnSelectCategories.setText("Select...");
        btnSelectCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCategoriesActionPerformed(evt);
            }
        });

        btnBrowseCommand.setText("Browse...");
        btnBrowseCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseCommandActionPerformed(evt);
            }
        });

        btnBrowseWorkDir.setText("Browse...");
        btnBrowseWorkDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseWorkDirActionPerformed(evt);
            }
        });

        btnPickIcon.setText("Select Icon...");
        btnPickIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPickIconActionPerformed(evt);
            }
        });

        lblIconPreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconPreview.setText("[ No Icon ]");
        lblIconPreview.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chkStartupNotify.setText("Use startup notification");

        chkTerminal.setText("Run in terminal");

        chkShowHidden.setSelected(true);
        chkShowHidden.setText("Show hidden files in file pickers");

        btnCreate.setText("Create / Save");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOpen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addComponent(txtComment)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCommand)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowseCommand))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtWorkDir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowseWorkDir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIconPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPickIcon))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCategories)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelectCategories))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkShowHidden)
                                    .addComponent(chkTerminal)
                                    .addComponent(chkStartupNotify))
                                .addGap(0, 150, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpen)
                    .addComponent(btnClear))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseCommand))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtWorkDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseWorkDir))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPickIcon)
                    .addComponent(lblIconPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectCategories))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(chkStartupNotify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkTerminal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkShowHidden)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Open .desktop File to Edit");
        chooser.setFileHidingEnabled(!chkShowHidden.isSelected());
        chooser.setFileFilter(new FileNameExtensionFilter("Desktop Entry Files (*.desktop)", "desktop"));

        File defaultDir = new File(System.getProperty("user.home"), ".local/share/applications");
        if (defaultDir.exists()) {
            chooser.setCurrentDirectory(defaultDir);
        }

        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            try {
                openDesktopFile(selectedFile);
            } catch (Exception ex) {
                logger.log(Level.SEVERE, "Failed to parse .desktop file", ex);
                JOptionPane.showMessageDialog(this,
                        "Error reading .desktop file:\n" + ex.getMessage(),
                        "Open Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSelectCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCategoriesActionPerformed
        javax.swing.JDialog dialog = new javax.swing.JDialog(this, "Select Categories", true);
        dialog.setLayout(new java.awt.BorderLayout(10, 10));

        javax.swing.JPanel listPanel = new javax.swing.JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        listPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        String[] standardCategories = {
            "AudioVideo", "Development", "Education", "Game", 
            "Graphics", "Network", "Office", "Settings", "System", "Utility"
        };

        String currentCats = txtCategories.getText().trim();
        java.util.List<javax.swing.JCheckBox> checkBoxes = new java.util.ArrayList<>();

        for (String cat : standardCategories) {
            javax.swing.JCheckBox cb = new javax.swing.JCheckBox(cat);
            if (currentCats.contains(cat + ";") || currentCats.contains(cat)) {
                cb.setSelected(true);
            }
            checkBoxes.add(cb);
            listPanel.add(cb);
        }

        javax.swing.JPanel customPanel = new javax.swing.JPanel(new java.awt.BorderLayout(5, 5));
        customPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 5, 10));
        customPanel.add(new javax.swing.JLabel("Custom (semicolon separated):"), java.awt.BorderLayout.WEST);
        javax.swing.JTextField txtCustom = new javax.swing.JTextField();
        customPanel.add(txtCustom, java.awt.BorderLayout.CENTER);

        javax.swing.JPanel centerPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        centerPanel.add(listPanel, java.awt.BorderLayout.CENTER);
        centerPanel.add(customPanel, java.awt.BorderLayout.SOUTH);

        javax.swing.JPanel btnPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        javax.swing.JButton btnOk = new javax.swing.JButton("OK");
        javax.swing.JButton btnDialogCancel = new javax.swing.JButton("Cancel");

        btnOk.addActionListener(e -> {
            StringBuilder sb = new StringBuilder();
            for (javax.swing.JCheckBox cb : checkBoxes) {
                if (cb.isSelected()) {
                    sb.append(cb.getText()).append(";");
                }
            }
            String custom = txtCustom.getText().trim();
            if (!custom.isEmpty()) {
                for (String part : custom.split(";")) {
                    String trimmed = part.trim();
                    if (!trimmed.isEmpty()) {
                        sb.append(trimmed).append(";");
                    }
                }
            }
            txtCategories.setText(sb.toString());
            dialog.dispose();
        });

        btnDialogCancel.addActionListener(e -> dialog.dispose());

        btnPanel.add(btnOk);
        btnPanel.add(btnDialogCancel);

        dialog.add(centerPanel, java.awt.BorderLayout.CENTER);
        dialog.add(btnPanel, java.awt.BorderLayout.SOUTH);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnSelectCategoriesActionPerformed

    private void btnBrowseCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseCommandActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select Command / Executable");
        chooser.setFileHidingEnabled(!chkShowHidden.isSelected());
        String currentPath = txtCommand.getText().trim();
        if (!currentPath.isEmpty()) {
            File currentFile = new File(currentPath);
            if (currentFile.exists()) {
                chooser.setSelectedFile(currentFile);
            }
        }
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            txtCommand.setText(selectedFile.getAbsolutePath());
            if (txtWorkDir.getText().trim().isEmpty()) {
                File parent = selectedFile.getParentFile();
                if (parent != null) {
                    txtWorkDir.setText(parent.getAbsolutePath());
                }
            }
        }
    }//GEN-LAST:event_btnBrowseCommandActionPerformed

    private void btnBrowseWorkDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseWorkDirActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select Working Directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setFileHidingEnabled(!chkShowHidden.isSelected());
        String currentPath = txtWorkDir.getText().trim();
        if (!currentPath.isEmpty()) {
            File currentDir = new File(currentPath);
            if (currentDir.exists()) {
                chooser.setCurrentDirectory(currentDir);
            }
        }
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedDir = chooser.getSelectedFile();
            txtWorkDir.setText(selectedDir.getAbsolutePath());
        }
    }//GEN-LAST:event_btnBrowseWorkDirActionPerformed

    private void btnPickIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPickIconActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select Icon File");
        chooser.setFileHidingEnabled(!chkShowHidden.isSelected());
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files (*.png, *.svg, *.xpm, *.ico)", "png", "svg", "xpm", "ico", "jpg", "jpeg");
        chooser.setFileFilter(filter);
        
        File defaultIconDir = new File("/usr/share/pixmaps");
        if (!defaultIconDir.exists()) {
            defaultIconDir = new File("/usr/share/icons");
        }
        if (defaultIconDir.exists()) {
            chooser.setCurrentDirectory(defaultIconDir);
        }
        
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            txtIcon.setText(selectedFile.getAbsolutePath());
            updateIconPreview();
        }
    }//GEN-LAST:event_btnPickIconActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String name = txtName.getText().trim();
        String command = txtCommand.getText().trim();
        
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Name for the launcher.", "Input Error", JOptionPane.WARNING_MESSAGE);
            txtName.requestFocus();
            return;
        }

        if (command.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Command for the launcher.", "Input Error", JOptionPane.WARNING_MESSAGE);
            txtCommand.requestFocus();
            return;
        }

        String comment = txtComment.getText().trim();
        String workDir = txtWorkDir.getText().trim();
        String icon = txtIcon.getText().trim();
        String categories = txtCategories.getText().trim();
        if (!categories.isEmpty() && !categories.endsWith(";")) {
            categories += ";";
        }
        
        boolean startupNotify = chkStartupNotify.isSelected();
        boolean terminal = chkTerminal.isSelected();

        String userHome = System.getProperty("user.home");
        File defaultDir = new File(userHome, ".local/share/applications");
        if (!defaultDir.exists()) {
            defaultDir.mkdirs();
        }
        if (!defaultDir.exists()) {
            defaultDir = new File(userHome, "Desktop");
        }
        if (!defaultDir.exists()) {
            defaultDir = new File(userHome);
        }

        String sanitizedName = name.replaceAll("[^a-zA-Z0-9._-]", "_").toLowerCase();
        if (sanitizedName.isEmpty()) {
            sanitizedName = "launcher";
        }
        File suggestedFile = new File(defaultDir, sanitizedName + ".desktop");

        JFileChooser chooser = new JFileChooser(defaultDir);
        chooser.setDialogTitle("Save .desktop File");
        chooser.setFileHidingEnabled(!chkShowHidden.isSelected());
        chooser.setSelectedFile(suggestedFile);
        chooser.setFileFilter(new FileNameExtensionFilter("Desktop Entry Files (*.desktop)", "desktop"));

        int result = chooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File destFile = chooser.getSelectedFile();
            if (!destFile.getName().toLowerCase().endsWith(".desktop")) {
                destFile = new File(destFile.getParentFile(), destFile.getName() + ".desktop");
            }

            if (destFile.exists()) {
                int confirm = JOptionPane.showConfirmDialog(this,
                        "File '" + destFile.getName() + "' already exists.\nDo you want to overwrite it?",
                        "Confirm Overwrite",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (confirm != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            try {
                saveDesktopFile(destFile, name, comment, command, workDir, icon, categories, terminal, startupNotify);
                destFile.setExecutable(true, false);

                JOptionPane.showMessageDialog(this,
                        "Launcher successfully created at:\n" + destFile.getAbsolutePath(),
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                
                clearFields();
            } catch (Exception ex) {
                logger.log(Level.SEVERE, "Failed to create .desktop file", ex);
                JOptionPane.showMessageDialog(this,
                        "Error saving file:\n" + ex.getMessage(),
                        "Save Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void openDesktopFile(File file) throws Exception {
        java.util.List<String> lines = java.nio.file.Files.readAllLines(file.toPath(), StandardCharsets.UTF_8);
        
        String name = "";
        String comment = "";
        String exec = "";
        String path = "";
        String icon = "";
        String categories = "";
        boolean terminal = false;
        boolean startupNotify = false;
        boolean inDesktopEntry = false;

        for (String line : lines) {
            line = line.trim();
            if (line.isEmpty() || line.startsWith("#")) {
                continue;
            }
            if (line.startsWith("[") && line.endsWith("]")) {
                inDesktopEntry = line.equalsIgnoreCase("[Desktop Entry]");
                continue;
            }
            if (!inDesktopEntry) {
                continue;
            }

            int eqIdx = line.indexOf('=');
            if (eqIdx <= 0) {
                continue;
            }

            String key = line.substring(0, eqIdx).trim();
            String val = line.substring(eqIdx + 1).trim();

            if (key.equalsIgnoreCase("Name")) {
                name = val;
            } else if (key.equalsIgnoreCase("Comment")) {
                comment = val;
            } else if (key.equalsIgnoreCase("Exec")) {
                exec = val;
            } else if (key.equalsIgnoreCase("Path")) {
                path = val;
            } else if (key.equalsIgnoreCase("Icon")) {
                icon = val;
            } else if (key.equalsIgnoreCase("Categories")) {
                categories = val;
            } else if (key.equalsIgnoreCase("Terminal")) {
                terminal = val.equalsIgnoreCase("true") || val.equals("1") || val.equalsIgnoreCase("yes");
            } else if (key.equalsIgnoreCase("StartupNotify")) {
                startupNotify = val.equalsIgnoreCase("true") || val.equals("1") || val.equalsIgnoreCase("yes");
            }
        }

        txtName.setText(name);
        txtComment.setText(comment);
        txtCommand.setText(exec);
        txtWorkDir.setText(path);
        txtIcon.setText(icon);
        txtCategories.setText(categories);
        chkTerminal.setSelected(terminal);
        chkStartupNotify.setSelected(startupNotify);
        updateIconPreview();

        setTitle("Create Launcher - Editing: " + file.getName());
    }

    private void saveDesktopFile(File file, String name, String comment, String command,
                                 String workDir, String icon, String categories,
                                 boolean terminal, boolean startupNotify) throws Exception {
        StringBuilder sb = new StringBuilder();
        sb.append("[Desktop Entry]\n");
        sb.append("Version=1.0\n");
        sb.append("Type=Application\n");
        sb.append("Name=").append(name).append("\n");
        
        if (!comment.isEmpty()) {
            sb.append("Comment=").append(comment).append("\n");
        }
        
        sb.append("Exec=").append(command).append("\n");
        
        if (!workDir.isEmpty()) {
            sb.append("Path=").append(workDir).append("\n");
        }
        
        if (!icon.isEmpty()) {
            sb.append("Icon=").append(icon).append("\n");
        }
        
        if (!categories.isEmpty()) {
            sb.append("Categories=").append(categories).append("\n");
        }
        
        sb.append("Terminal=").append(terminal ? "true" : "false").append("\n");
        sb.append("StartupNotify=").append(startupNotify ? "true" : "false").append("\n");

        try (OutputStreamWriter writer = new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8)) {
            writer.write(sb.toString());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseCommand;
    private javax.swing.JButton btnBrowseWorkDir;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnPickIcon;
    private javax.swing.JButton btnSelectCategories;
    private javax.swing.JCheckBox chkShowHidden;
    private javax.swing.JCheckBox chkStartupNotify;
    private javax.swing.JCheckBox chkTerminal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIconPreview;
    private javax.swing.JTextField txtCategories;
    private javax.swing.JTextField txtCommand;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextField txtIcon;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtWorkDir;
    // End of variables declaration//GEN-END:variables
}
